---
title: "Data Cleaning"
output: html_document
---


```{r}
library(tidyverse)
library(skimr)
library(visdat)
library(GGally)
library(knitr)

load("tech_data.Rdata")
```

```{r}
tech_biom1 = tech_biom[1:54] #remove XXX_MISS variables
```

```{r}
vis_miss(tech_biom1)
```

```{r}
### column missingness

column_missingness = c()
for (i in 1:ncol(tech_biom1)) {
  num_missing = colSums(is.na(tech_biom1[i]))
  variable = colnames(tech_biom1)[i]
  observations = nrow(tech_biom1)
  missingness_proportion = round(num_missing / observations, 3)
  column_missingness = c(column_missingness, variable, num_missing, observations, missingness_proportion)
}
col_df = matrix(column_missingness, ncol=4, byrow=TRUE)
colnames(col_df) = c("Variable", "Missingness Count", "Total", "Missingness Proportion")
col_df = data.frame(col_df)

good_variables = col_df$Variable[col_df$Missingness.Proportion < 0.3] 
col_df2 = col_df[col_df$Variable %in% good_variables,] # table of all "good" columns

tech_biom2 = tech_biom1[good_variables] # filtering for good columns only, arbitrary 30% column missingness threshold


### row missingness

tech_biom3 = tech_biom2[rowSums(is.na(tech_biom2)) == 0,] # filtering for good rows only, removing all rows with N/A
vis_miss(tech_biom3)
```
```{r}
kable(head(col_df))
```
```{r}
save(tech_biom3, file="cleaned_biom.Rdata")
```




