---
title: "Feasibility Analysis"
output: html_document
---


```{r Preprocessing, warning = FALSE, message = FALSE, include = FALSE}
library(tidyverse)
library(skimr)
library(visdat)
library(GGally)
library(knitr)
library(corrplot)
library(glmnet)
library(brglm)

load("combined_data.Rdata")
```

```{r Viewing combined data, warning = FALSE}
class(combined_data)
DT::datatable(combined_data)
```

```{r Viewing Systolic blood pressure, warning = FALSE}
systol_data=combined_data[ , !(names(combined_data) %in% c("ABSPID", "ABSHID", "BMISC", "HCHOLBC", "CHOLRESB", "CHOLNTR", "HDLCHREB", "LDLNTR", "LDLRESB", "DIASTOL", "HSUGBC", "BMR", "EIBMR1", "EIBMR2"))]
# How/why did you choose to omit these particular variables?

class(systol_data)
DT::datatable(systol_data)
```

```{r Correlation plot of variables}
M = cor(systol_data)
corrplot(M, method = 'color', order = 'alphabet') 
```


```{r Initial null and full models}
systol_M0 = lm(SYSTOL ~ 1, data = systol_data)
systol_M1 = lm(SYSTOL ~ ., data = systol_data)
```

```{r Forward AIC on null model}
systol_forw <- step(systol_M0, scope = list(lower = systol_M0, upper = systol_M1), direction = "forward", k = 2, trace = 0)

summary(systol_forw)
```

```{r Created GLM}
y = systol_data$SYSTOL
x = combined_data[ , !(names(combined_data) %in% c("ABSPID", "ABSHID", "BMISC", "SYSTOL", "HCHOLBC", "CHOLRESB", "CHOLNTR", "HDLCHREB", "LDLNTR", "LDLRESB", "DIASTOL", "HSUGBC", "BMR", "EIBMR1", "EIBMR2"))]
# Once again where do these variables come from? (I haven't done any lectures yet, is this concept from it?)

model <- glmnet(x, y, alpha = 0) # purpose of this variable? (We aren't using it anywhere)
print(model)

best_model <- glmnet(x, y, alpha = 0, lambda = best_lambda) # How do we find this best_lambda?
print(best_model)
```

```{r}
summary(y)
```

```{r Predict Systolic blood pressure levels using the GLM}
y_predicted <- predict(model, s = best_lambda, newx = x)
sst <- sum((y - mean(y))^2)
sse <- sum((y_predicted - y)^2)
rsq <- 1 - sse/sst
rsq
```
```{r}
r2 = brglm(y~x)
summary(r2)
```

